services:
  leaderboard:
    container_name: leaderboard-container
    image: leaderboard-image
    ports:
      - '8000:8000'

  redis:
    container_name: redis
    image: redis
    stdin_open: true
    tty: true
    network_mode: container:leaderboard-container

  postgres:
    container_name: postgres
    image: postgres:16
    stdin_open: true
    tty: true
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=DB_PASS
    network_mode: container:leaderboard-container

