services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  postgres:
    container_name: postgres
    image: postgres:16
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=DB_PASS
  leaderboard-container:
    container_name: leaderboard-container
    image: leaderboard-image
    depends_on:
      - redis
      - postgres
    ports:
      - '8000:8000'
      - '5432:5432'
      - '6379:6379'