services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  postgres:
    image: postgresql:17
    ports:
      - '5432:5432'
  leaderboard-container:
    image: leaderboard-image
    depends_on:
      - redis
    ports:
      - '8000:8000'
      - '5432:5432'
      - '6379:6379'